/*
 * Torque API Reference
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jenkinsci.plugins.torque.api;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


public class EnvironmentDefinitionResponse {
  @SerializedName("metadata")
  private EnvironmentMetadataResponse metadata = null;

  @SerializedName("inputs")
  private List<EnvironmentNameValueResponse> inputs = null;

  @SerializedName("tags")
  private List<SandboxTag> tags = null;

  public EnvironmentDefinitionResponse metadata(EnvironmentMetadataResponse metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  
  public EnvironmentMetadataResponse getMetadata() {
    return metadata;
  }

  public void setMetadata(EnvironmentMetadataResponse metadata) {
    this.metadata = metadata;
  }

  public EnvironmentDefinitionResponse inputs(List<EnvironmentNameValueResponse> inputs) {
    this.inputs = inputs;
    return this;
  }

  public EnvironmentDefinitionResponse addInputsItem(EnvironmentNameValueResponse inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<EnvironmentNameValueResponse>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  
  public List<EnvironmentNameValueResponse> getInputs() {
    return inputs;
  }

  public void setInputs(List<EnvironmentNameValueResponse> inputs) {
    this.inputs = inputs;
  }

  public EnvironmentDefinitionResponse tags(List<SandboxTag> tags) {
    this.tags = tags;
    return this;
  }

  public EnvironmentDefinitionResponse addTagsItem(SandboxTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<SandboxTag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  
  public List<SandboxTag> getTags() {
    return tags;
  }

  public void setTags(List<SandboxTag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentDefinitionResponse environmentDefinitionResponse = (EnvironmentDefinitionResponse) o;
    return Objects.equals(this.metadata, environmentDefinitionResponse.metadata) &&
        Objects.equals(this.inputs, environmentDefinitionResponse.inputs) &&
        Objects.equals(this.tags, environmentDefinitionResponse.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, inputs, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentDefinitionResponse {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
