/*
 * Torque API Reference
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jenkinsci.plugins.torque.api;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


public class EnvironmentDetailsResponse {
  @SerializedName("id")
  public String id = null;

  @SerializedName("definition")
  private EnvironmentDefinitionResponse definition = null;

  @SerializedName("state")
  public EnvironmentStateResponse state = null;

  @SerializedName("computed_status")
  public String computedStatus = null;

  public EnvironmentDetailsResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EnvironmentDetailsResponse definition(EnvironmentDefinitionResponse definition) {
    this.definition = definition;
    return this;
  }

   /**
   * Get definition
   * @return definition
  **/
  
  public EnvironmentDefinitionResponse getDefinition() {
    return definition;
  }

  public void setDefinition(EnvironmentDefinitionResponse definition) {
    this.definition = definition;
  }

  public EnvironmentDetailsResponse state(EnvironmentStateResponse state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  
  public EnvironmentStateResponse getState() {
    return state;
  }

  public void setState(EnvironmentStateResponse state) {
    this.state = state;
  }

  public EnvironmentDetailsResponse computedStatus(String computedStatus) {
    this.computedStatus = computedStatus;
    return this;
  }

   /**
   * Get computedStatus
   * @return computedStatus
  **/
  
  public String getComputedStatus() {
    return computedStatus;
  }

  public void setComputedStatus(String computedStatus) {
    this.computedStatus = computedStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnvironmentDetailsResponse environmentDetailsResponse = (EnvironmentDetailsResponse) o;
    return Objects.equals(this.id, environmentDetailsResponse.id) &&
        Objects.equals(this.definition, environmentDetailsResponse.definition) &&
        Objects.equals(this.state, environmentDetailsResponse.state) &&
        Objects.equals(this.computedStatus, environmentDetailsResponse.computedStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, definition, state, computedStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QualiColonyGatewayApiModelResponsesEnvironmentDetailsResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    computedStatus: ").append(toIndentedString(computedStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
