/*
 * Torque API Reference
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.jenkinsci.plugins.torque.api;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class GrainActivityResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("log")
  private String log = null;

  @SerializedName("execution")
  private TimeDataResponse execution = null;

  @SerializedName("errors")
  private List<EnvironmentErrorResponse> errors = null;

  public GrainActivityResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GrainActivityResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GrainActivityResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public GrainActivityResponse log(String log) {
    this.log = log;
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  
  public String getLog() {
    return log;
  }

  public void setLog(String log) {
    this.log = log;
  }

  public GrainActivityResponse execution(TimeDataResponse execution) {
    this.execution = execution;
    return this;
  }

   /**
   * Get execution
   * @return execution
  **/
  
  public TimeDataResponse getExecution() {
    return execution;
  }

  public void setExecution(TimeDataResponse execution) {
    this.execution = execution;
  }

  public GrainActivityResponse errors(List<EnvironmentErrorResponse> errors) {
    this.errors = errors;
    return this;
  }

  public GrainActivityResponse addErrorsItem(EnvironmentErrorResponse errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<EnvironmentErrorResponse>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  
  public List<EnvironmentErrorResponse> getErrors() {
    return errors;
  }

  public void setErrors(List<EnvironmentErrorResponse> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrainActivityResponse grainActivityResponse = (GrainActivityResponse) o;
    return Objects.equals(this.id, grainActivityResponse.id) &&
        Objects.equals(this.name, grainActivityResponse.name) &&
        Objects.equals(this.status, grainActivityResponse.status) &&
        Objects.equals(this.log, grainActivityResponse.log) &&
        Objects.equals(this.execution, grainActivityResponse.execution) &&
        Objects.equals(this.errors, grainActivityResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, status, log, execution, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnvironmentGrainActivityResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    execution: ").append(toIndentedString(execution)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
